name: ubuntu
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse" -y
          sudo apt-get install libsdl2-dev -y

      - name: Build & Install
        run: |
          sudo mkdir cmake-build-release
          cd cmake-build-release
          sudo cmake -DCMAKE_BUILD_TYPE=Release ..
          sudo cmake --install .
      - name: Build all examples
        run: |
          cd cmake-build-release
          sudo cmake -DCMAKE_BUILD_TYPE=Release ..
          sudo cmake --build .
